- name: Install packages - nginx, certbot, python3-certbot-nginx
  ansible.builtin.apt:
    pkg:
      - nginx
      - certbot
      - python3-certbot-nginx
  notify: (handler) nginx systemd

- name: Replace nginx configuration file (nginx.conf)
  ansible.builtin.template:
    src: templates/nginx.conf
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"

- name: Replace nginx default site conf
  ansible.builtin.template:
    src: templates/default-site.conf
    dest: "/etc/nginx/sites-available/default"
    mode: "0644"
  notify: (handler) nginx reload
