- name: (handler) nginx systemd
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: (handler) nginx reload
  ansible.builtin.service:
    name: nginx
    state: reloaded
